### ISSUE TITLE
Add instruction how to use it with Termux

### ISSUE THREAD

**Issue by Symbian9** [yeyeto2788/OpenNoteScannerPDF#7]
Add instruction how to use this Python script on mobile device with *Termux* app

- https://github.com/termux/termux-app

**Comment by yeyeto2788** [comment]
@Symbian9 sorry for the delay on the reply.

Thanks for opening the issue, I have created a wiki page a while ago https://github.com/yeyeto2788/OpenNoteScannerPDF/wiki/How-to-run-the-code-on-Termux-Android-app

Hope it helps and if there is anything I can help with just, let me know.

Regards.
